using Personas;
using Colegio;
using static System.Runtime.InteropServices.JavaScript.JSType;
Salon salon = new Salon();
Estudiante E1=new Estudiante();
Estudiante E2 = new Estudiante();
Estudiante E3 = new Estudiante();
Entrenador Eu =new Entrenador();
Console.WriteLine("Inserte nombre el alumno 1: ");
string E1.Name = Console.ReadLine();
Console.WriteLine("Inserte nombre el alumno 2: ");
string E2.Name = Console.ReadLine();
Console.WriteLine("Inserte nombre el alumno 3: ");
string E3.Name = Console.ReadLine();
Console.WriteLine("Inserte nombre del entrenador: ");
string Eu.Name = Console.ReadLine();
salon.PasarAsistencia();
E1.Estudia();
Eu.HaceEjercicio();
//hola
